### PR TITLE
feat: load an ijs file for real

### PR DESCRIPTION
**Pull request by FauxFaux**
```
jr 0.1.0
   0!:10 <'/home/faux/ins/j903/system/main/stdlib.ijs'
0
   ('ba';'+') stringreplace 'ababa'
[a, +, +]
```

```
   0!:0 <'aoc1.ijs'
0
   d1p1
10000
   ('ba';'+') sr 'ababa'
[a, +, +]
```

I would like to make it clear, very clear, that I am aware that The Adverb Catastrophe is probably making this significantly worse than it should. But, I'm not touching that, no no no. I think there might even be a Conjunction Catastrophe.

Also, maybe it should be `ctx.exc(verb, x, y)`, not `verb.exec(ctx, x, y)`. Luckily Rust dgaf, afaik.

### CODE REVIEW

**Comment by AshyIsMe** [comment]
Testing `stringreplace` from `~/j903/system/main/stdlib.ijs`:

Manually stepping through this (the old school type it all out way): `('foo';'a') stringreplace 'foobar'`:
First error seems to occur here:
- https://github.com/jsoftware/jsource/blob/master/jlibrary/system/main/stdlib.ijs#L1494
- `    cx=. (i pick hit) -. set, ,bgn -/ i.ln`

```
   NB. jr repl
   i
0
   pick
> @ {
   hit
|[0]|
   ln
3
   bgn
[]
   set
[]
   cx=. (i pick hit) -. set, ,bgn -/ i.ln
error: dyadic / not implemented yet (legacy)
cause: adverb: "/"
cause: evaluating 2 dyad
cause: evaluating "cx=. (i pick hit) -. set, ,bgn -/ i.ln"
```

**Comment by AshyIsMe** [comment]
Next case:

`('a';'b') stringreplace 'abcd'`

Fails at:
- `  if. 0 e. $ndx do. txt return. end.` https://github.com/jsoftware/jsource/blob/master/jlibrary/system/main/stdlib.ijs#L1473

```
   NB. jr repl
   x
|[a, b]|
   y
[a, b, c, d]
   txt
[a, b, c, d]
   hit
[0, 1, 1, 1]
   old
|[a]|
   new
|[b]|
   ndx
0
   $ndx
[]
   0 e. $ndx
error: Condition failed: `ido.shape().len() == 1` (0 vs 1)
cause: applying function to cells
cause: dyadic "e."
cause: evaluating 2 dyad
cause: evaluating "0 e. $ndx"

```

**Comment by FauxFaux** [comment]
I reworked framing fill and take's idea of empty a bit.

Now,

```
('foo';'a') stringreplace 'foobar'
```

tries to run `0,(0 $ 0)`, which is at least slightly odd, and not supported.
```
cause: can only append atoms or lists, not BoolArray(0) BoolArray([])
cause: dyadic ","
```

```
   0,(0 $ 0)
0
   $ (0,(0 $ 0))
1
```

---

And,
```
('a';'b') stringreplace 'abcd'
```

..apparently tries to run `{` with multiple x-s, which is also lazily not implemented.

**Comment by FauxFaux** [comment]
That fixes those tests, but `stringreplace` is still in the same state, with those two nonces.

**Comment by FauxFaux** [comment]
Special casing `,` is sufficient, HAH.

**Comment by AshyIsMe** [comment]
My vote is that this PR should be merged.

**Pull request merged**
